# docker-compose.yml

version: '3'

networks:
  aulaPhpFatec:
    external: true
    name: aulaPhpFatec

services:
  postgres:
    image: postgres:latest
    networks:
      - aulaPhpFatec
    environment:
      - POSTGRES_DB=webdev
      - POSTGRES_USER=userbanco
      - POSTGRES_PASSWORD=senhabanco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U userbanco -d webdev"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: ["postgres", "-c", "max_connections=300", "-c", "listen_addresses=*"]
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php-nginx:
    image: nginx:latest
    networks:
      - aulaPhpFatec
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      postgres:
        condition: service_healthy

  php-fpm:
    image: php:8.2-fpm
    networks:
      - aulaPhpFatec
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    command: ["bash", "-c", "docker-php-ext-install pdo_pgsql && php-fpm"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@email.com
      - PGADMIN_DEFAULT_PASSWORD=senhapgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_fatec:/var/lib/pgadmin
    networks:
      - aulaPhpFatec

volumes:
  pg_data_fatec:
  pgadmin_data_fatec: